fix postgis scripts are available

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -316,6 +316,10 @@ jobs:
             sleep 0.1
           done
 
+      - name: Check DEM scripts are available in docker image
+        run: |
+          docker-compose run --rm web sh -c 'command -v raster2pgsql >/dev/null 2>&1 || { echo >&2 "raster2pgsql command not found."; exit 1; }'
+
       - name: E2E test
         run: |
           /home/runner/work/Geotrek-admin/Geotrek-admin/cypress/node_modules/.bin/cypress run -P /home/runner/work/Geotrek-admin/Geotrek-admin/cypress --record --key 64a5a9b3-9869-4a2f-91e4-e3cd27c2f564
@@ -387,6 +391,13 @@ jobs:
           sudo unlink /etc/nginx/sites-enabled/default
           sudo apt-get install --no-install-recommends /home/runner/work/Geotrek-admin/Geotrek-admin/*.deb || exit 0;
           sudo systemctl restart nginx
+
+      - name: Check raster2pgsql command
+        run: |
+          if ! command -v raster2pgsql &> /dev/null; then
+            echo "raster2pgsql could not be found"
+            exit 1
+          fi
 
       - name: Load Data
         run: |
